export const SITE_LAYOUTS = [
  {
    id: 'editorial-luxe',
    name: 'Editorial Luxe',
    desc: 'Elegante e arioso, con taglio editoriale premium e toni caldi controllati.',
    emoji: '📰',
    colors: ['#f5f1ea', '#201a17', '#a06a42'],
    font_heading: 'Cormorant Garamond',
    font_body: 'Source Sans 3',
    color_palette: {
      background: '#f5f1ea',
      surface: '#fffdf9',
      text: '#201a17',
      text_muted: '#6e6258',
      primary: '#a06a42',
      secondary: '#efe1d2',
      primary_gradient: 'linear-gradient(135deg, #c79063, #8a5634)',
    },
    ui_style: {
      radius: '18px',
      card_shadow: '0 12px 40px rgba(0,0,0,0.08)',
      glassmorphism: false,
    },
    layout_recipe: {
      hero: 'editorial',
      nav: 'transparent',
      cards: 'editorial',
      density: 'airy',
    },
    base_models: ['editorial-luxe'],
  },
  {
    id: 'neo-brutal-pop',
    name: 'Neo Brutal Pop',
    desc: 'Gerarchie forti, carattere deciso e accenti netti senza effetto template.',
    emoji: '⚡',
    colors: ['#fff8e7', '#111111', '#ff6b2c'],
    font_heading: 'Space Grotesk',
    font_body: 'Inter',
    color_palette: {
      background: '#fff8e7',
      surface: '#ffffff',
      text: '#111111',
      text_muted: '#4f4b45',
      primary: '#ff6b2c',
      secondary: '#ffd9c8',
      primary_gradient: 'linear-gradient(135deg, #ff8f5a, #ff5b1f)',
    },
    ui_style: {
      radius: '8px',
      card_shadow: '0 14px 0 rgba(17,17,17,0.12)',
      glassmorphism: false,
    },
    layout_recipe: {
      hero: 'split',
      nav: 'solid',
      cards: 'bold',
      density: 'balanced',
    },
    base_models: ['neo-brutal-pop'],
  },
  {
    id: 'dark-cinematic',
    name: 'Dark Cinematic',
    desc: 'Scuro premium, profondo e controllato, con luce morbida e atmosfera.',
    emoji: '🎬',
    colors: ['#0b0b0f', '#f5f5f0', '#d4a574'],
    font_heading: 'Sora',
    font_body: 'DM Sans',
    color_palette: {
      background: '#0b0b0f',
      surface: '#14141b',
      text: '#f5f5f0',
      text_muted: '#b7b2ab',
      primary: '#d4a574',
      secondary: '#2a221d',
      primary_gradient: 'linear-gradient(135deg, #e8bb88, #9f6a3d)',
    },
    ui_style: {
      radius: '20px',
      card_shadow: '0 20px 60px rgba(0,0,0,0.28)',
      glassmorphism: true,
    },
    layout_recipe: {
      hero: 'immersive',
      nav: 'transparent',
      cards: 'cinematic',
      density: 'airy',
    },
    base_models: ['dark-cinematic'],
  },
  {
    id: 'warm-humanist',
    name: 'Warm Humanist',
    desc: 'Umano, rassicurante e leggibile, ottimo per personal brand e professionisti.',
    emoji: '🌿',
    colors: ['#fcf7f0', '#243028', '#3d8b6d'],
    font_heading: 'Fraunces',
    font_body: 'Source Sans 3',
    color_palette: {
      background: '#fcf7f0',
      surface: '#fffdf8',
      text: '#243028',
      text_muted: '#647067',
      primary: '#3d8b6d',
      secondary: '#dceee5',
      primary_gradient: 'linear-gradient(135deg, #60b08f, #2f6d58)',
    },
    ui_style: {
      radius: '24px',
      card_shadow: '0 12px 36px rgba(36,48,40,0.08)',
      glassmorphism: false,
    },
    layout_recipe: {
      hero: 'human',
      nav: 'floating',
      cards: 'soft',
      density: 'airy',
    },
    base_models: ['warm-humanist'],
  },
  {
    id: 'tech-clarity',
    name: 'Tech Clarity',
    desc: 'Pulito, moderno e preciso, con feeling product-grade e accenti blu sobri.',
    emoji: '🧠',
    colors: ['#f3f7fb', '#16202a', '#2563eb'],
    font_heading: 'Plus Jakarta Sans',
    font_body: 'Inter',
    color_palette: {
      background: '#f3f7fb',
      surface: '#ffffff',
      text: '#16202a',
      text_muted: '#5f6b76',
      primary: '#2563eb',
      secondary: '#dbe8ff',
      primary_gradient: 'linear-gradient(135deg, #4f8cff, #1d4ed8)',
    },
    ui_style: {
      radius: '16px',
      card_shadow: '0 10px 30px rgba(15,23,42,0.08)',
      glassmorphism: false,
    },
    layout_recipe: {
      hero: 'product',
      nav: 'solid',
      cards: 'product',
      density: 'balanced',
    },
    base_models: ['tech-clarity'],
  },
];
